/* Generated by Opal 0.6.2 */
(function($opal) {
  var self = $opal.top, $scope = $opal, nil = $opal.nil, $breaker = $opal.breaker, $slice = $opal.slice, $klass = $opal.klass;

  $opal.add_stubs(['$require_all', '$new', '$init', '$update', '$render', '$sleep', '$close', '$map']);
  self.$require_all("lib");
  return (function($base, $super) {
    function $TheGame(){};
    var self = $TheGame = $klass($base, $super, 'TheGame', $TheGame);

    var def = self._proto, $scope = self._scope;

    def.engine = def.window = nil;
    def.$setup = function() {
      var $a, self = this;

      self.engine = (($a = $scope.Engine) == null ? $opal.cm('Engine') : $a).$new();
      return self.window = (($a = $scope.Window) == null ? $opal.cm('Window') : $a).$new(self.engine);
    };

    def.$window = function() {
      var self = this;

      return self.window;
    };

    def.$start = function() {
      var $a, $b, self = this;

      self.window.$init();
      try {
      while ((($b = true) !== nil && (!$b._isBoolean || $b == true))) {
      self.engine.$update();
      self.window.$render();
      self.$sleep(0.01);}
      } finally {
      self.window.$close()
      };
    };

    return (def.$map = function() {
      var self = this;

      return self.engine.$map();
    }, nil) && 'map';
  })(self, null);
})(Opal);

//# sourceMappingURL=/__opal_source_maps__/the_game.js.map
;
